export const toolInfo = {
  name: 'NanoID Generator',
  description:
    'Generate cryptographically secure NanoID-style random IDs with customizable length and alphabet.',
  slug: 'nanoid-generator',
};

export const relatedTools = [
  { name: 'UUID Generator', href: '/tools/uuid-generator' },
  { name: 'Password Generator', href: '/tools/password-generator' },
  { name: 'Hash Generator', href: '/tools/hash-generator' },
  { name: 'Slug Generator', href: '/tools/slug-generator' },
];

export const features = [
  'Generate cryptographically secure random IDs',
  'Customizable length (1–128 characters)',
  'Choose from lowercase, uppercase, numbers, and symbols',
  'Bulk generate up to 100 IDs at once',
  'Uses Web Crypto API (crypto.getRandomValues)',
  'Works entirely offline — no data leaves your browser',
];

export const howToSteps = [
  'Set the desired ID length (default: 21)',
  'Select which character sets to include in the alphabet',
  'Choose how many IDs to generate',
  'Click "Generate" to create the IDs',
  'Copy individual IDs or all at once',
];

export const examples = [
  {
    title: 'Default NanoID (21 chars)',
    input: 'Length: 21, Alphabet: a-z A-Z 0-9 -_',
    output: 'V1StGXR8_Z5jdHi6B-myT',
  },
  {
    title: 'Short numeric ID (8 chars)',
    input: 'Length: 8, Alphabet: 0-9',
    output: '48271653',
  },
  {
    title: 'URL-safe slug (12 chars)',
    input: 'Length: 12, Alphabet: a-z 0-9',
    output: 'k7f9x2m4a8n3',
  },
];

export const explanation = {
  title: 'What Is NanoID?',
  content: [
    'NanoID is a tiny, secure, URL-friendly unique string ID generator. Originally created as a JavaScript library by Andrey Sitnik, it has become a popular alternative to UUID for generating random identifiers. The default NanoID is 21 characters long and uses an alphabet of 64 URL-safe characters (A-Z, a-z, 0-9, - and _), providing 126 bits of entropy — comparable to UUID v4.',
    'The key advantage of NanoID over UUID is size. A UUID v4 is 36 characters long (including dashes) and uses only hexadecimal characters. A NanoID achieves similar collision resistance in just 21 characters by using a larger alphabet. This makes NanoIDs more compact in URLs, database columns, log files, and anywhere string length matters.',
    'This tool uses the Web Crypto API (crypto.getRandomValues) for cryptographically secure random number generation. This is the same entropy source used by NanoID in production — not Math.random(), which is predictable and unsuitable for security-sensitive identifiers. Every ID generated by this tool is as random as one generated by the official NanoID library.',
    'The customizable alphabet feature lets you tailor the output to your needs. Need numeric-only IDs for order numbers? Use digits only. Want lowercase slugs? Use lowercase letters. Need maximum entropy per character? Use the full default alphabet. The collision probability depends on both the length and the alphabet size — the tool gives you full control over this trade-off.',
    'All ID generation happens in your browser using the Web Crypto API. No server requests, no logging, no data collection. Generate production-ready IDs with confidence that the entropy source is secure and the output never leaves your device.',
  ],
};

export const faqItems = [
  {
    question: 'How does NanoID compare to UUID?',
    answer:
      'NanoID is shorter (21 vs 36 chars), URL-safe by default, and customizable. UUID v4 has 122 bits of entropy; NanoID with default settings has 126 bits. Both are suitable for most applications, but NanoID is more compact.',
  },
  {
    question: 'Are these IDs cryptographically secure?',
    answer:
      'Yes. This tool uses crypto.getRandomValues() from the Web Crypto API, which provides cryptographically secure random numbers. This is the same method used by the official NanoID library.',
  },
  {
    question: 'What length should I use?',
    answer:
      'The default of 21 characters provides 126 bits of entropy with the default alphabet — plenty for most applications. For less critical use cases, 10–12 characters may suffice. For high-security identifiers, consider 24+ characters.',
  },
  {
    question: 'Can I use these as database primary keys?',
    answer:
      'Yes. NanoIDs are commonly used as primary keys in databases. They are URL-safe, compact, and have extremely low collision probability at the default length. However, unlike sequential IDs, they do not sort by creation time.',
  },
  {
    question: 'Is the generation done locally?',
    answer:
      'Yes. All IDs are generated entirely in your browser using the Web Crypto API. Nothing is sent to any server.',
  },
];
